services:
  db:
    image: postgres:latest
    container_name: album_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile
    container_name: album_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/myapp
    volumes:
      - ./api:/app
      - node_modules_api:/app/node_modules
    command: npm run dev
    working_dir: /app

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    container_name: album_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - node_modules_client:/app/node_modules
    depends_on:
      - api
    working_dir: /app
    command: npm run dev -- --host

volumes:
  pgdata:
  node_modules_api:
  node_modules_client:
