
services:
  db:
    image: postgres:latest
    container_name: album_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile
    container_name: album_api
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PORT: ${API_PORT}  # アプリ側でも参照できるように
    volumes:
      - ./api:/app
      - node_modules_api:/app/node_modules
    command: npm run dev
    working_dir: /app

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    container_name: album_client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./client:/app
      - node_modules_client:/app/node_modules
    depends_on:
      - api
    working_dir: /app
    command: npm run dev -- --host

volumes:
  pgdata:
  node_modules_api:
  node_modules_client:
