services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile
    container_name: hono_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/myapp
    volumes:
      - ./api:/app
      - node_modules_api:/app/node_modules
    command: npm run dev
    working_dir: /app

volumes:
  pgdata:
  node_modules_api:
