openapi: 3.0.4
info:
  title: 花道展写真共有用アルバム
  version: 1.0.0

tags:
  - name: exhibition
    description: 花展の情報を取得するAPI

paths:
  /exhibitions:
    get:
      tags:
        - exhibition
      summary: 花展の一覧
      description: 花展の一覧を取得する。花展は開催日の降順。
      operationId: listExhibitions
      responses:
        '200':
          $ref: '#/components/responses/ExhibitionsResponse'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /exhibitions/{exhibitionId}:
    get:
      tags:
        - exhibition
      summary: 花展の取得
      description: 花展の情報を取得する
      operationId: getExhibition
      parameters:
        - $ref: '#/components/parameters/ExhibitionIdParam'
      responses:
        '200':
          $ref: '#/components/responses/ExhibitionResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /exhibitions/{exhibitionId}/works:
    get:
      tags:
        - exhibition
      summary: 花展の作品の一覧
      description: 花展ごとの作品の一覧を登録の作品の登録日の昇順で取得する
      operationId: listExhibitionWorks
      parameters:
        - $ref: '#/components/parameters/ExhibitionIdParam'
      responses:
        '200':
          $ref: '#/components/responses/WorkListItemsResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          description: Unexpected error

  /exhibitions/{exhibitionId}/works/{workId}:
    get:
      tags:
        - exhibition
      summary: 花展の作品の取得
      description: 花展ごとの作品の情報を取得する
      operationId: getExhibitionWork
      parameters:
        - $ref: '#/components/parameters/ExhibitionIdParam'
        - $ref: '#/components/parameters/WorkIdParam'
      responses:
        '200':
          $ref: '#/components/responses/WorkListItemResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          description: Unexpected error

  /arrangers/{arrangerId}:
    get:
      tags:
        - arranger
      summary: 作者の情報の取得
      description: 作者の情報を取得する
      operationId: getArranger
      parameters:
        - $ref: '#/components/parameters/ArrangerIdParam'
      responses:
        '200':
          $ref: '#/components/responses/ArrangerResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          description: Unexpected error

  /arrangers/{arrangerId}/works:
    get:
      tags:
        - arranger
      summary: 作者の作品の一覧
      description: 作者ごとの作品の一覧を作品の登録日の昇順で取得する
      operationId: listArrangerWorks
      parameters:
        - $ref: '#/components/parameters/ArrangerIdParam'
      responses:
        '200':
          $ref: '#/components/responses/WorkListItemsResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /arrangers/{arrangerId}/works/{workId}:
    get:
      tags:
        - arranger
      summary: 作者の作品の取得
      description: 作者ごとの作品の情報を取得する
      operationId: getArrangerWork
      parameters:
        - $ref: '#/components/parameters/ArrangerIdParam'
        - $ref: '#/components/parameters/WorkIdParam'
      responses:
        '200':
          $ref: '#/components/responses/WorkListItemResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /materials/{materialId}:
    get:
      tags:
        - material
      summary: 材料の情報の取得
      description: 材料の情報を取得する
      operationId: getMaterial
      parameters:
        - $ref: '#/components/parameters/MaterialIdParam'
      responses:
        '200':
          $ref: '#/components/responses/MaterialResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /materials/{materialId}/works:
    get:
      tags:
        - material
      summary: 材料の作品の一覧
      description: 材料ごとの作品の一覧を作品の登録日の昇順で取得する
      operationId: listMaterialWorks
      parameters:
        - $ref: '#/components/parameters/MaterialIdParam'
      responses:
        '200':
          $ref: '#/components/responses/WorkListItemsResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /materials/{materialId}/works/{workId}:
    get:
      tags:
        - material
      summary: 材料の作品の取得
      description: 材料ごとの作品の情報を取得する
      operationId: getMaterialWork
      parameters:
        - $ref: '#/components/parameters/MaterialIdParam'
        - $ref: '#/components/parameters/WorkIdParam'
      responses:
        '200':
          $ref: '#/components/responses/WorkListItemResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /categories/{categoryId}:
    get:
      tags:
        - category
      summary: カテゴリの情報の取得
      description: カテゴリの情報を取得する
      operationId: getCategory
      parameters:
        - $ref: '#/components/parameters/CategoryIdParam'
      responses:
        '200':
          $ref: '#/components/responses/CategoryResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /categories/{categoryId}/works:
    get:
      tags:
        - category
      summary: カテゴリの作品の一覧
      description: カテゴリごとの作品の一覧を作品の登録日の昇順で取得する
      operationId: listCategoryWorks
      parameters:
        - $ref: '#/components/parameters/CategoryIdParam'
      responses:
        '200':
          $ref: '#/components/responses/WorkListItemsResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /categories/{categoryId}/works/{workId}:
    get:
      tags:
        - category
      summary: カテゴリの作品の取得
      description: カテゴリごとの作品の情報を取得する
      operationId: getCategoryWork
      parameters:
        - $ref: '#/components/parameters/CategoryIdParam'
        - $ref: '#/components/parameters/WorkIdParam'
      responses:
        '200':
          $ref: '#/components/responses/WorkListItemResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /seasons/{seasonId}:
    get:
      tags:
        - season
      summary: 季節の情報の取得
      description: 季節の情報を取得する
      operationId: getSeason
      parameters:
        - $ref: '#/components/parameters/SeasonIdParam'
      responses:
        '200':
          $ref: '#/components/responses/SeasonResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /seasons/{seasonId}/works:
    get:
      tags:
        - season
      summary: 季節の作品の一覧
      description: 季節ごとの作品の一覧を作品の登録日の昇順で取得する
      operationId: listSeasonWorks
      parameters:
        - $ref: '#/components/parameters/SeasonIdParam'
      responses:
        '200':
          $ref: '#/components/responses/WorkListItemsResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /seasons/{seasonId}/works/{workId}:
    get:
      tags:
        - season
      summary: 季節の作品の取得
      description: 季節ごとの作品の情報を取得する
      operationId: getSeasonWork
      parameters:
        - $ref: '#/components/parameters/SeasonIdParam'
        - $ref: '#/components/parameters/WorkIdParam'
      responses:
        '200':
          $ref: '#/components/responses/WorkListItemResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/UnexpectedError'

components:
  schemas:
    Exhibition:
      type: object
      properties:
        id:
          type: integer
          description: 花展のID
        name:
          type: string
          description: 花展の名前
        started_date:
          type: string
          format: date
          description: 花展の開始日
        ended_date:
          type: string
          format: date
          description: 花展の終了日
      required:
        - id
        - name
        - started_date
        - ended_date
      example:
        id: 1
        name: "春の花展"
        started_date: "2023-03-01"
        ended_date: "2023-03-31"
    Work:
      type: object
      properties:
        id:
          type: integer
          description: 作品のID
        title:
          type: string
          description: 作品のタイトル
          nullable: true
        exhibition_id:
          type: integer
          description: 花展のID
          nullable: true
        arranger_id:
          type: integer
          description: 作者のID
        season_id:
          type: integer
          description: 季節のID
        material_ids:
          type: array
          items:
            type: integer
          description: 使用された材料のIDのリスト
        category_id:
          type: integer
          description: カテゴリのID
        image_urls:
          type: array
          items:
            type: string
            format: uri
          description: 作品の画像URLのリスト
        created_at:
          type: string
          format: date-time
          description: 作品の登録日時
      required:
        - id
        - title
        - exhibition_id
        - arranger_id
        - material_ids
        - season_id
        - category_id
        - image_urls
      example:
        id: 1
        title: "桜のアレンジメント"
        arranger_id: 1
        material_ids: [1, 2, 3]
        season_id: 1
        category_id: 1
        image_urls:
          - "https://example.com/image1"
          - "https://example.com/image2"
    WorkListItem:
      type: object
      properties:
        work:
          $ref: '#/components/schemas/Work'
        navigation:
          $ref: '#/components/schemas/WorkListNavigation'
      required:
        - work
        - navigation
    WorkListNavigation:
      type: object
      properties:
        next:
          type: integer
          description: 次の作品のID
          nullable: true
        previous:
          type: integer
          description: 前の作品のID
          nullable: true
      required:
        - next
        - previous
      example:
        next: 2
        previous: null
    Arranger:
      type: object
      properties:
        id:
          type: integer
          description: 作者のID
        name:
          type: string
          description: 作者の名前
      required:
        - id
        - name
      example:
        id: 1
        name: "山田太郎"
    Material:
      type: object
      properties:
        id:
          type: integer
          description: 材料のID
        name:
          type: string
          description: 材料の名前
      required:
        - id
        - name
      example:
        id: 1
        name: "芍薬"
    Category:
      type: object
      properties:
        id:
          type: integer
          description: カテゴリのID
        name:
          type: string
          description: カテゴリの名前
      required:
        - id
        - name
      example:
        id: 1
        name: "格花"
    Season:
      type: object
      properties:
        id:
          type: integer
          description: 季節のID
        name:
          type: string
          description: 季節の名前
      required:
        - id
        - name
      example:
        id: 1
        name: "春"
  parameters:
    ExhibitionIdParam:
      name: exhibitionId
      in: path
      required: true
      description: 花展のID
      schema:
        type: integer
    WorkIdParam:
      name: workId
      in: path
      required: true
      description: 作品のID
      schema:
        type: integer
    ArrangerIdParam:
      name: arrangerId
      in: path
      required: true
      description: 作者のID
      schema:
        type: integer
    MaterialIdParam:
      name: materialId
      in: path
      required: true
      description: 材料のID
      schema:
        type: integer
    CategoryIdParam:
      name: categoryId
      in: path
      required: true
      description: カテゴリのID
      schema:
        type: integer
    SeasonIdParam:
      name: seasonId
      in: path
      required: true
      description: 季節のID
      schema:
        type: integer
  responses:
    UnexpectedError:
      description: An unexpected error occurred
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Resource not found"
    ExhibitionResponse:
      description: A single exhibition
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Exhibition'
    ExhibitionsResponse:
      description: A list of exhibitions
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Exhibition'
            example:
              - id: 1
                name: "春の花展"
                started_date: "2023-03-01"
                ended_date: "2023-03-31"
              - id: 2
                name: "夏の花展"
                started_date: "2023-06-01"
                ended_date: "2023-06-30"
              - id: 3
                name: "秋の花展"
                started_date: "2023-09-01"
                ended_date: "2023-09-30"
              - id: 4
                name: "冬の花展"
                started_date: "2023-12-01"
                ended_date: "2023-12-31"
    WorkListItemsResponse:
      description: A list of work list items
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/WorkListItem'
            example:
              - work:
                  id: 1
                  title: "桜のアレンジメント"
                  arranger_id: 1
                  material_ids: [1, 2, 3]
                  category_id: 1
                  season_id: 1
                  image_urls:
                    - "https://example.com/image1"
                    - "https://example.com/image2"
                navigation:
                  next: 2
                  previous: null
              - work:
                  id: 2
                  title: "梅の花束"
                  arranger_id: 2
                  material_ids: [4, 5]
                  season_id: 1
                  category_id: 2
                  image_urls:
                    - "https://example.com/image3"
                navigation:
                  next: 3
                  previous: 1
              - work:
                  id: 3
                  title: null
                  arranger_id: 3
                  material_ids: [6]
                  season_id: 2
                  category_id: 1
                  image_urls:
                    - "https://example.com/image4"
                navigation:
                  next: null
                  previous: 2
    WorkListItemResponse:
      description: A single work list item
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WorkListItem'
    ArrangerResponse:
      description: A single arranger
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Arranger'
    MaterialResponse:
      description: A single material
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Material'
    CategoryResponse:
      description: A single category
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Category'
    SeasonResponse:
      description: A single season
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Season'
