services:
  db:
    image: postgres:16
    container_name: api_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  api:
    build: .
    container_name: api_server
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:3000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - .:/app
    command: npm run dev

volumes:
  pgdata:
